# Day 1  Assignment 1: NumPy Array Slicing

All supplied questions are answered below.

In [1]:
import numpy as np
arr = np.array([[[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24],[25,26,27,28,29]],[[30,31,32,33,34],[35,36,37,38,39],[40,41,42,43,44],[45,46,47,48,49]],[[50,51,52,53,54],[55,56,57,58,59],[60,61,62,63,64],[65,66,67,68,69]]])
arr1 = np.array([[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55],[60,61,62,63,64,65]])
print('3D shape:', arr.shape, '2D shape:', arr1.shape)

3D shape: (3, 4, 5) 2D shape: (6, 6)


In [ ]:
# 3D Sections AG
answers_3d = {
 'individual_elements': [arr[0,0,0], arr[0,2,4], arr[1,1,2], arr[1,2,3], arr[2,0,4], arr[2,3,1], arr[2,1,3], arr[1,3,4]],
 'requested_rows': [arr[0,1,:], arr[1,2,:], arr[2,3,:]],
 'matrices': [arr[0], arr[1], arr[2]],
 'columns': [arr[0,:,0], arr[1,:,2], arr[2,:,4]],
 'first_two_matrices': arr[:2], 'last_two_matrices': arr[1:],
 'first_two_rows': arr[:,:2,:], 'last_two_rows': arr[:,2:,:],
 'first_three_columns': arr[:,:,:3], 'last_two_columns': arr[:,:,3:],
 'advanced_1': arr[0,:2,:3], 'advanced_2': arr[1,2:,2:],
 'advanced_3': arr[2,1:,:2], 'advanced_4': arr[0,:2,3:],
 'alternate_matrices': arr[::2], 'alternate_rows': arr[:,::2,:], 'alternate_columns': arr[:,:,::2],
 'first_column': arr[:,:,0], 'last_column': arr[:,:,-1], 'middle_row': arr[:,2,:], 'middle_column': arr[:,:,2],
 'reverse_matrices': arr[::-1], 'reverse_rows': arr[:,::-1,:], 'reverse_columns': arr[:,:,::-1]
}
for question, answer in answers_3d.items(): print(f'\n{question}:\n{answer}')


individual_elements:
[np.int64(10), np.int64(24), np.int64(37), np.int64(43), np.int64(54), np.int64(66), np.int64(58), np.int64(49)]

requested_rows:
[array([15, 16, 17, 18, 19]), array([40, 41, 42, 43, 44]), array([65, 66, 67, 68, 69])]

matrices:
[array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]]), array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])]

columns:
[array([10, 15, 20, 25]), array([32, 37, 42, 47]), array([54, 59, 64, 69])]

first_two_matrices:
[[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]

last_two_matrices:
[[[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58

In [ ]:
# 2D questions 117
answers_2d = {
 'alternate_rows': arr1[::2,:], 'alternate_columns': arr1[:,::2], 'first_column': arr1[:,0], 'last_column': arr1[:,-1],
 'middle_row': arr1[3,:], 'middle_column': arr1[:,3], 'first_three_rows': arr1[:3,:], 'last_three_rows': arr1[3:,:],
 'first_three_columns': arr1[:,:3], 'last_three_columns': arr1[:,3:], 'reverse_rows': arr1[::-1,:],
 'reverse_columns': arr1[:,::-1], 'reverse_both': arr1[::-1,::-1], 'center_block': arr1[1:4,2:5],
 'alternate_center': arr1[::2,1::2], 'last_two_rows': arr1[-2:,:], 'last_two_columns': arr1[:,-2:]
}
for question, answer in answers_2d.items(): print(f'\n{question}:\n{answer}')


alternate_rows:
[[10 11 12 13 14 15]
 [30 31 32 33 34 35]
 [50 51 52 53 54 55]]

alternate_columns:
[[10 12 14]
 [20 22 24]
 [30 32 34]
 [40 42 44]
 [50 52 54]
 [60 62 64]]

first_column:
[10 20 30 40 50 60]

last_column:
[15 25 35 45 55 65]

middle_row:
[40 41 42 43 44 45]

middle_column:
[13 23 33 43 53 63]

first_three_rows:
[[10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]

last_three_rows:
[[40 41 42 43 44 45]
 [50 51 52 53 54 55]
 [60 61 62 63 64 65]]

first_three_columns:
[[10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]
 [60 61 62]]

last_three_columns:
[[13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]]

reverse_rows:
[[60 61 62 63 64 65]
 [50 51 52 53 54 55]
 [40 41 42 43 44 45]
 [30 31 32 33 34 35]
 [20 21 22 23 24 25]
 [10 11 12 13 14 15]]

reverse_columns:
[[15 14 13 12 11 10]
 [25 24 23 22 21 20]
 [35 34 33 32 31 30]
 [45 44 43 42 41 40]
 [55 54 53 52 51 50]
 [65 64 63 62 61 60]]

reverse_both:
[[65 64 63 62 61 60]
 [55 54 53 