# Assignment 3 – Tensor Python Tasks


In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)
rng = np.random.default_rng(42)

print("NumPy version:", np.__version__)

NumPy version: 2.5.2


## Task 1 — Create a Tensor

In [2]:
readings = np.array([25.2, 25.5, 24.9, 26.1, 25.8])

print("Tensor:", readings)
print("Shape:", readings.shape)
print("Number of dimensions:", readings.ndim)
print("Number of elements:", readings.size)

Tensor: [25.2 25.5 24.9 26.1 25.8]
Shape: (5,)
Number of dimensions: 1
Number of elements: 5


## Task 2 — From Vector to Matrix

In [3]:
temperature = [25, 26, 25, 27, 28]
pressure = [101, 102, 101, 103, 104]
humidity = [60, 62, 61, 63, 64]
vibration = [0.2, 0.3, 0.2, 0.4, 0.5]

sensor_data = np.array([
    temperature,
    pressure,
    humidity,
    vibration
]).T

print("Tensor:\n", sensor_data)
print("Shape:", sensor_data.shape)
print("Number of dimensions:", sensor_data.ndim)
print("First time step:", sensor_data[0])
print("Temperature readings:", sensor_data[:, 0])
print("Vibration readings:", sensor_data[:, 3])

print("\nAxis meaning:")
print("Axis 0 = time steps (5)")
print("Axis 1 = sensors (4): temperature, pressure, humidity, vibration")

Tensor:
 [[ 25.  101.   60.    0.2]
 [ 26.  102.   62.    0.3]
 [ 25.  101.   61.    0.2]
 [ 27.  103.   63.    0.4]
 [ 28.  104.   64.    0.5]]
Shape: (5, 4)
Number of dimensions: 2
First time step: [ 25.  101.   60.    0.2]
Temperature readings: [25. 26. 25. 27. 28.]
Vibration readings: [0.2 0.3 0.2 0.4 0.5]

Axis meaning:
Axis 0 = time steps (5)
Axis 1 = sensors (4): temperature, pressure, humidity, vibration


## Task 3 — Create a 3D Tensor

In [4]:
# Shape: Machine × Time × Sensor
machines = rng.uniform(0, 100, size=(10, 5, 4))

print("Shape:", machines.shape)

# Zero-based indexing: machine 3 -> index 2, time step 2 -> index 1.
# Sensor 1 is treated as temperature in this synthetic example.
print("Temperature reading of machine 3 at time step 2:", machines[2, 1, 0])

print("\nAll sensor readings of machine 5:")
print(machines[4])

print("\nAll machines at time step 1:")
print(machines[:, 0, :])

print("\nSensor 4 from all machines and all time steps:")
print(machines[:, :, 3])

Shape: (10, 5, 4)
Temperature reading of machine 3 at time step 2: 83.2259801395201

All sensor readings of machine 5:
[[66.431 40.639 81.402 16.697]
 [ 2.271  9.005 72.236 46.188]
 [16.127 50.104 15.231 69.632]
 [44.616 38.102 30.151 63.028]
 [36.181  8.765 11.801 96.19 ]]

All machines at time step 1:
[[77.396 43.888 85.86  69.737]
 [75.809 35.453 97.07  89.312]
 [43.715 83.268 70.027 31.237]
 [66.84  47.11  56.524 76.5  ]
 [66.431 40.639 81.402 16.697]
 [90.858 69.971 26.587 96.918]
 [58.41  64.985  8.444 41.581]
 [48.666 49.071 93.783 57.173]
 [10.774 91.601 23.021  3.741]
 [89.079 89.345 51.886 31.593]]

Sensor 4 from all machines and all time steps:
[[69.737 78.606 92.676 22.724 63.166]
 [89.312  4.38  96.751 18.947 66.981]
 [31.237 28.833  0.736 78.073 11.453]
 [76.5   30.395 40.853 28.138 78.39 ]
 [16.697 46.188 69.632 63.028 96.19 ]
 [96.918 27.224 20.236 85.661 62.731]
 [41.581 14.452 92.512  2.28   8.273]
 [57.173 52.067 89.616 67.224 76.865]
 [ 3.741 80.825 51.506  4.491 74

## Task 4 — Indexing a Tensor

In [5]:
X = np.arange(24).reshape(2, 3, 4)

print("X =\n", X)
print("\nX[0] =\n", X[0])
print("\nX[1] =\n", X[1])
print("\nX[0, 0] =", X[0, 0])
print("\nX[0, 0, 0] =", X[0, 0, 0])

print("\nAnswers:")
print("1. Shape of X:", X.shape)
print("2. X[0] represents the first block; shape:", X[0].shape)
print("3. X[0,0] represents the first row of the first block; shape:", X[0, 0].shape)
print("4. X[0,0,0] represents one scalar element:", X[0, 0, 0])

X =
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

X[0] =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

X[1] =
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

X[0, 0] = [0 1 2 3]

X[0, 0, 0] = 0

Answers:
1. Shape of X: (2, 3, 4)
2. X[0] represents the first block; shape: (3, 4)
3. X[0,0] represents the first row of the first block; shape: (4,)
4. X[0,0,0] represents one scalar element: 0


## Task 5 — Slicing

In [6]:
X = np.arange(60).reshape(3, 4, 5)

first_block = X[0]
first_row_every_block = X[:, 0, :]
third_element_every_row_every_block = X[:, :, 2]
last_two_elements = X[:, :, -2:]

print("X shape:", X.shape)
print("\nFirst block X[0]:\n", first_block)
print("\nFirst row from every block X[:, 0, :]:\n", first_row_every_block)
print("\nThird element from every row and block X[:, :, 2]:\n", third_element_every_row_every_block)
print("\nLast two elements X[:, :, -2:]:\n", last_two_elements)

print("\nResulting shapes:")
print("First block:", first_block.shape)
print("First row from every block:", first_row_every_block.shape)
print("Third element from every row/block:", third_element_every_row_every_block.shape)
print("Last two elements:", last_two_elements.shape)

X shape: (3, 4, 5)

First block X[0]:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

First row from every block X[:, 0, :]:
 [[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]]

Third element from every row and block X[:, :, 2]:
 [[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]

Last two elements X[:, :, -2:]:
 [[[ 3  4]
  [ 8  9]
  [13 14]
  [18 19]]

 [[23 24]
  [28 29]
  [33 34]
  [38 39]]

 [[43 44]
  [48 49]
  [53 54]
  [58 59]]]

Resulting shapes:
First block: (4, 5)
First row from every block: (3, 5)
Third element from every row/block: (3, 4)
Last two elements: (3, 4, 2)


## Task 6 — Image Tensor

In [7]:
height, width, channels = 128, 128, 3
image = rng.integers(0, 256, size=(height, width, channels), dtype=np.uint8)

red = image[:, :, 0]
green = image[:, :, 1]
blue = image[:, :, 2]

print("Image shape:", image.shape)
print("Red channel shape:", red.shape)
print("Green channel shape:", green.shape)
print("Blue channel shape:", blue.shape)
print("Maximum pixel value:", image.max())
print("Minimum pixel value:", image.min())

Image shape: (128, 128, 3)
Red channel shape: (128, 128)
Green channel shape: (128, 128)
Blue channel shape: (128, 128)
Maximum pixel value: 255
Minimum pixel value: 0


## Task 7 — Batch of Images

In [8]:
images = rng.integers(0, 256, size=(32, 128, 128, 3), dtype=np.uint8)

first_image = images[0]
first_10_images = images[:10]
red_all = images[:, :, :, 0]
pixel_50_50 = images[:, 50, 50, :]

print("Batch shape:", images.shape)
print("First image shape:", first_image.shape)
print("First 10 images shape:", first_10_images.shape)
print("Red channel from all images shape:", red_all.shape)
print("Pixel (50, 50) from every image shape:", pixel_50_50.shape)

print("\nPixel (50, 50) from every image:\n", pixel_50_50)

Batch shape: (32, 128, 128, 3)
First image shape: (128, 128, 3)
First 10 images shape: (10, 128, 128, 3)
Red channel from all images shape: (32, 128, 128)
Pixel (50, 50) from every image shape: (32, 3)

Pixel (50, 50) from every image:
 [[ 25  69 244]
 [243 166 222]
 [ 27 136 136]
 [171  64 234]
 [ 86 107 144]
 [235 199  21]
 [164 246 120]
 [137 255 191]
 [167  57 128]
 [121 122 149]
 [233 255 199]
 [ 99 129 215]
 [ 26 143  45]
 [166 228  82]
 [179 247   7]
 [210 227 253]
 [ 77 150  23]
 [107 238  86]
 [121 140 164]
 [ 33 222  15]
 [ 56  49 250]
 [109  80 248]
 [128 177  36]
 [ 30 209  25]
 [ 89  11  76]
 [136   5 182]
 [ 92 179  94]
 [241 224 122]
 [207 199  31]
 [ 19  11 157]
 [183 221 239]
 [219 218 249]]


## Task 8 — Reshape

In [9]:
X = np.arange(24)

reshapes = [(4, 6), (2, 3, 4), (6, 4), (24,)]

for shape in reshapes:
    Y = X.reshape(shape)
    print("=" * 50)
    print("Shape:", shape)
    print("Tensor:\n", Y)
    print("Number of dimensions:", Y.ndim)
    print("Number of elements:", Y.size)

print("\nExplanation:")
print("Reshaping changes how the same elements are organized into axes.")
print("It cannot change the total number of elements; therefore every valid reshape must contain 24 elements.")

Shape: (4, 6)
Tensor:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Number of dimensions: 2
Number of elements: 24
Shape: (2, 3, 4)
Tensor:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Number of dimensions: 3
Number of elements: 24
Shape: (6, 4)
Tensor:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Number of dimensions: 2
Number of elements: 24
Shape: (24,)
Tensor:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Number of dimensions: 1
Number of elements: 24

Explanation:
Reshaping changes how the same elements are organized into axes.
It cannot change the total number of elements; therefore every valid reshape must contain 24 elements.


## Task 9 — Reshape vs Transpose

In [10]:
X = np.arange(24).reshape(2, 3, 4)

reshape_result = X.reshape(3, 2, 4)
transpose_result = X.transpose(1, 0, 2)

print("Original X:\n", X)
print("\nX.reshape(3, 2, 4):\n", reshape_result)
print("\nX.transpose(1, 0, 2):\n", transpose_result)

print("\nSame shape?", reshape_result.shape == transpose_result.shape)
print("Same values in the same positions?", np.array_equal(reshape_result, transpose_result))

print("\nConclusion:")
print("No. Reshape changes the grouping/order interpretation of the existing sequence.")
print("Transpose permutes existing axes while preserving their axis-wise relationships.")

Original X:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

X.reshape(3, 2, 4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

X.transpose(1, 0, 2):
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

Same shape? True
Same values in the same positions? False

Conclusion:
No. Reshape changes the grouping/order interpretation of the existing sequence.
Transpose permutes existing axes while preserving their axis-wise relationships.


## Task 10 — Broadcasting

In [11]:
X = np.ones((3, 4))
b = np.array([10, 20, 30, 40])

addition = X + b
multiplication = X * b

print("X + b:\n", addition)
print("\nX * b:\n", multiplication)
print("\nShapes:")
print("X:", X.shape)
print("b:", b.shape)
print("X + b:", addition.shape)
print("X * b:", multiplication.shape)

print("\nWhy it works:")
print("The (4,) vector matches the final dimension of (3, 4).")
print("NumPy broadcasts b across all 3 rows.")

X + b:
 [[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]

X * b:
 [[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]]

Shapes:
X: (3, 4)
b: (4,)
X + b: (3, 4)
X * b: (3, 4)

Why it works:
The (4,) vector matches the final dimension of (3, 4).
NumPy broadcasts b across all 3 rows.


## Task 11 — Broadcasting with Sensor Data

In [12]:
X = rng.normal(size=(100, 10))

calibration = np.array([1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4])

corrected = X - calibration

print("Original shape:", X.shape)
print("Calibration shape:", calibration.shape)
print("Corrected shape:", corrected.shape)
print("\nFirst sample before correction:", X[0])
print("First sample after correction:", corrected[0])

Original shape: (100, 10)
Calibration shape: (10,)
Corrected shape: (100, 10)

First sample before correction: [-0.711 -1.972 -0.906 -1.268 -1.103  0.498 -0.45  -1.177  0.629  1.725]
First sample after correction: [-1.911 -2.772 -2.006 -1.768 -2.003 -0.502 -1.15  -2.477  0.029  1.325]


## Task 12 — Tensor Aggregation

In [13]:
X = rng.normal(size=(100, 20, 5))

mean_across_time = X.mean(axis=1)
mean_across_sensors = X.mean(axis=2)
mean_across_machines = X.mean(axis=0)
max_sensor_value_across_time = X.max(axis=1)
std_across_time = X.std(axis=1)

print("X shape:", X.shape)
print("\nPredicted and actual result shapes:")
print("1. Mean across time:        ", mean_across_time.shape, " (100, 5)")
print("2. Mean across sensors:     ", mean_across_sensors.shape, " (100, 20)")
print("3. Mean across machines:    ", mean_across_machines.shape, " (20, 5)")
print("4. Max across time:         ", max_sensor_value_across_time.shape, " (100, 5)")
print("5. Std across time:         ", std_across_time.shape, " (100, 5)")

X shape: (100, 20, 5)

Predicted and actual result shapes:
1. Mean across time:         (100, 5)  (100, 5)
2. Mean across sensors:      (100, 20)  (100, 20)
3. Mean across machines:     (20, 5)  (20, 5)
4. Max across time:          (100, 5)  (100, 5)
5. Std across time:          (100, 5)  (100, 5)


## Task 13 — Normalize a Tensor

In [14]:
X = rng.normal(size=(100, 20, 5))

# Mean and standard deviation for each sensor across machines and time.
sensor_mean = X.mean(axis=(0, 1), keepdims=True)
sensor_std = X.std(axis=(0, 1), keepdims=True)

X_normalized = (X - sensor_mean) / sensor_std

verified_mean = X_normalized.mean(axis=(0, 1))
verified_std = X_normalized.std(axis=(0, 1))

print("Original shape:", X.shape)
print("Sensor mean shape:", sensor_mean.shape)
print("Sensor std shape:", sensor_std.shape)
print("\nNormalized mean for each sensor:", verified_mean)
print("Normalized std for each sensor:", verified_std)

print("\nMean approximately 0?", np.allclose(verified_mean, 0, atol=1e-7))
print("Std approximately 1?", np.allclose(verified_std, 1, atol=1e-7))

Original shape: (100, 20, 5)
Sensor mean shape: (1, 1, 5)
Sensor std shape: (1, 1, 5)

Normalized mean for each sensor: [ 0. -0. -0.  0.  0.]
Normalized std for each sensor: [1. 1. 1. 1. 1.]

Mean approximately 0? True
Std approximately 1? True


## Task 14 — Flattening

In [15]:
image = rng.random((28, 28, 3))
flat_image = image.reshape(2352)

batch = rng.random((64, 28, 28, 3))
flat_batch = batch.reshape(64, 2352)

print("Single image:", image.shape)
print("Flattened image:", flat_image.shape)
print("Batch:", batch.shape)
print("Flattened each image:", flat_batch.shape)

print("\nWhy not flatten the whole batch into (150528,)?")
print("Flattening the entire batch would remove the batch dimension.")
print("The model normally needs to keep the 64 individual samples separate.")

Single image: (28, 28, 3)
Flattened image: (2352,)
Batch: (64, 28, 28, 3)
Flattened each image: (64, 2352)

Why not flatten the whole batch into (150528,)?
Flattening the entire batch would remove the batch dimension.
The model normally needs to keep the 64 individual samples separate.


## Task 15 — Concatenation

In [16]:
visual_features = rng.normal(size=(32, 128))
sensor_features = rng.normal(size=(32, 64))

combined = np.concatenate([visual_features, sensor_features], axis=1)

print("Visual features:", visual_features.shape)
print("Sensor features:", sensor_features.shape)
print("Combined features:", combined.shape)

print("\nWhy concatenate along feature dimension?")
print("Both tensors have the same batch dimension (32).")
print("Their feature dimensions (128 and 64) can be joined along axis 1.")
print("Dimensions being concatenated must be compatible on the other axes.")

Visual features: (32, 128)
Sensor features: (32, 64)
Combined features: (32, 192)

Why concatenate along feature dimension?
Both tensors have the same batch dimension (32).
Their feature dimensions (128 and 64) can be joined along axis 1.
Dimensions being concatenated must be compatible on the other axes.


## Task 16 — Practical Mini Challenge: Sensor Dataset

In [17]:
X = rng.normal(size=(500, 60, 8))

print("Dataset shape:", X.shape)

# 1. Machine 10 (zero-based index 9)
machine_10 = X[9]

# 2. First 20 time steps from all machines
first_20_time_steps = X[:, :20, :]

# 3. Sensor 5 from all machines (zero-based index 4)
sensor_5 = X[:, :, 4]

# 4. Average value of every sensor across machines and time
average_every_sensor = X.mean(axis=(0, 1))

# 5. Average value at every time step across machines and sensors
average_every_time_step = X.mean(axis=(0, 2))

# 6. Machine with highest average sensor reading
machine_means = X.mean(axis=(1, 2))
highest_machine_index = np.argmax(machine_means)
highest_machine_number = highest_machine_index + 1

# 7. Normalize each sensor across machines and time
sensor_mean = X.mean(axis=(0, 1), keepdims=True)
sensor_std = X.std(axis=(0, 1), keepdims=True)
X_normalized = (X - sensor_mean) / sensor_std

# 8. Train/test split
X_train = X[:400]
X_test = X[400:]

print("\n1. Machine 10 shape:", machine_10.shape)
print("2. First 20 time steps shape:", first_20_time_steps.shape)
print("3. Sensor 5 shape:", sensor_5.shape)
print("4. Average of every sensor:", average_every_sensor)
print("5. Average at every time step shape:", average_every_time_step.shape)
print("6. Machine with highest average sensor reading:", highest_machine_number)
print("   Highest average:", machine_means[highest_machine_index])
print("7. Normalized tensor shape:", X_normalized.shape)
print("8. Training shape:", X_train.shape)
print("   Testing shape:", X_test.shape)

Dataset shape: (500, 60, 8)

1. Machine 10 shape: (60, 8)
2. First 20 time steps shape: (500, 20, 8)
3. Sensor 5 shape: (500, 60)
4. Average of every sensor: [ 0.008 -0.011 -0.008 -0.008  0.007 -0.004 -0.002 -0.005]
5. Average at every time step shape: (60,)
6. Machine with highest average sensor reading: 163
   Highest average: 0.1584730776499873
7. Normalized tensor shape: (500, 60, 8)
8. Training shape: (400, 60, 8)
   Testing shape: (100, 60, 8)


## Task 17 — PyTorch

In [18]:
import torch

X_torch = torch.arange(24).reshape(2, 3, 4)

print(X_torch)
print("\nShape:", X_torch.shape)
print("Number of dimensions:", X_torch.ndim)
print("Number of elements:", X_torch.numel())

X = torch.randn(32, 100, 768)

print("\nNew tensor shape:", X.shape)
print("A reasonable interpretation is:")
print("32  -> batch size / number of sequences")
print("100 -> number of tokens or time steps per sequence")
print("768 -> embedding dimension or features per token")

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Shape: torch.Size([2, 3, 4])
Number of dimensions: 3
Number of elements: 24

New tensor shape: torch.Size([32, 100, 768])
A reasonable interpretation is:
32  -> batch size / number of sequences
100 -> number of tokens or time steps per sequence
768 -> embedding dimension or features per token
